package com.careerpilot.ai.service;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.client.HttpStatusCodeException;
import org.springframework.web.client.RestTemplate;

import java.util.List;
import java.util.Map;

@Service
public class GeminiService {

    @Value("${gemini.api.key}")
    private String apiKey;

    @Value("${gemini.api.url}")
    private String apiUrl;

    private final RestTemplate restTemplate = new RestTemplate();

    public String generateResponse(String prompt) {
        try {
            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);

            Map<String, Object> requestBody = Map.of(
                "contents", List.of(
                    Map.of("parts", List.of(Map.of("text", prompt)))
                )
            );

            HttpEntity<Map<String, Object>> entity = new HttpEntity<>(requestBody, headers);

            String finalUrl = apiUrl + "?key=" + apiKey;

            ResponseEntity<Map> response = restTemplate.exchange(finalUrl, HttpMethod.POST, entity, Map.class);

            Map<String, Object> body = response.getBody();
            if (body == null) {
                return "No response received from AI.";
            }

            List<?> candidates = (List<?>) body.get("candidates");
            if (candidates == null || candidates.isEmpty()) {
                return "No content generated by Gemini.";
            }

            @SuppressWarnings("unchecked")
            Map<String, Object> candidate = (Map<String, Object>) candidates.get(0);

            @SuppressWarnings("unchecked")
            Map<String, Object> content = (Map<String, Object>) candidate.get("content");

            @SuppressWarnings("unchecked")
            List<Map<String, Object>> parts = (List<Map<String, Object>>) content.get("parts");

            Map<String, Object> part = parts.get(0);
            String text = part.get("text").toString();

            return cleanJsonText(text);

        } catch (HttpStatusCodeException ex) {
            System.out.println("Status: " + ex.getStatusCode());
            System.out.println("Body: " + ex.getResponseBodyAsString());
            return "An error occurred while contacting the AI: " + ex.getResponseBodyAsString();
        } catch (Exception ex) {
            System.out.println("Error: " + ex.getMessage());
            return "An error occurred while contacting the AI: " + ex.getMessage();
        }
    }

    private String cleanJsonText(String raw) {
        if (raw == null) return "";
        String cleaned = raw.replace("```json", "").replace("```", "").trim();
        if (cleaned.startsWith("{") && cleaned.endsWith("}")) {
            int firstBrace = cleaned.indexOf('{');
            int lastBrace = cleaned.lastIndexOf('}');
            if (firstBrace != -1 && lastBrace != -1 && lastBrace > firstBrace) {
                return cleaned.substring(firstBrace, lastBrace + 1);
            }
        }
        return cleaned;
    }

    public String improveResume(String resumeText) {
        String prompt = "Improve the following resume content, enhancing readability, impact, and ATS score:\n\n" + resumeText;
        return generateResponse(prompt);
    }

    public String generateCoverLetter(String resumeText, String jobDescription, String companyName) {
        String prompt = String.format(
            "Generate a highly persuasive, professional cover letter based on the following details:\nResume Context: %s\nJob Description / Role: %s\nTarget Company: %s\nInclude proper greeting, opening hook, key technical achievements match, and clear call-to-action.",
            resumeText != null && !resumeText.isBlank() ? resumeText : "Experienced Professional",
            jobDescription != null && !jobDescription.isBlank() ? jobDescription : "Target Role",
            companyName != null && !companyName.isBlank() ? companyName : "Hiring Company"
        );
        return generateResponse(prompt);
    }

    public String generateInterviewQuestions(String jobRole, String experienceLevel) {
        String prompt = String.format(
            "Return strictly valid JSON only without markdown formatting with exact keys: {\"technicalQuestions\":[{\"question\":\"...\",\"answer\":\"...\"}],\"hrQuestions\":[{\"question\":\"...\",\"answer\":\"...\"}],\"codingQuestions\":[{\"question\":\"...\",\"approach\":\"...\",\"solution\":\"...\"}],\"interviewTips\":[\"...\"],\"commonMistakes\":[\"...\"]} for a %s position with %s experience level.",
            jobRole, experienceLevel
        );
        return generateResponse(prompt);
    }

    public String generateJDMatch(String resumeText, String jobDescription) {
        String prompt = String.format(
            "Return strictly valid JSON only matching: {\"overallMatchScore\":85,\"matchLevel\":\"High\",\"matchedSkills\":[\"...\"],\"missingSkills\":[\"...\"],\"additionalSkills\":[\"...\"],\"atsScore\":82,\"atsKeywordsFound\":[\"...\"],\"missingATSKeywords\":[\"...\"],\"matchingProjects\":[\"...\"],\"recommendedProjects\":[\"...\"],\"experienceMatch\":\"Strong\",\"resumeStrengths\":[\"...\"],\"resumeWeaknesses\":[\"...\"],\"resumeImprovements\":[\"...\"],\"recommendedCourses\":[\"...\"],\"certifications\":[\"...\"],\"interviewPreparationTopics\":[\"...\"],\"hiringRecommendation\":\"Recommended\",\"overallFeedback\":\"...\"}\nResume: %s\nJob Description: %s",
            resumeText, jobDescription
        );
        return generateResponse(prompt);
    }

    public String evaluateMockInterview(String question, String answer, String jobRole) {
        String prompt = String.format(
            "Evaluate candidate answer for %s position. Return strictly valid JSON only: {\"score\":8,\"strengths\":\"...\",\"weaknesses\":\"...\",\"improvedAnswer\":\"...\",\"confidenceLevel\":\"High\"}\nQuestion: %s\nAnswer: %s",
            jobRole, question, answer
        );
        return generateResponse(prompt);
    }
}